### ISSUE TITLE
What am I doing wrong?

### ISSUE THREAD

**Issue by nappyjim** [pdong/node-contrib-inovelli-status-manager#13]
Hi.  Can you take a look at my flow and tell me what I am doing wrong.  LED color does not change, no error in debug.

`[{"id":"7329dbb4.98afe4","type":"tab","label":"Flow 1","disabled":false,"info":""},{"id":"755408d6.2374a8","type":"inovelli-status-manager","z":"7329dbb4.98afe4","name":"zwave","nodeid":"10","color":"70","level":"7","duration":"255","display":"1","switchtype":8,"x":280,"y":620,"wires":[["bd7b0397.14b18"]]},{"id":"b5eb1b57.0d25b8","type":"inject","z":"7329dbb4.98afe4","name":"","props":[{"p":"payload"},{"p":"topic","vt":"str"}],"repeat":"","crontab":"","once":false,"onceDelay":0.1,"topic":"","payload":"","payloadType":"date","x":110,"y":620,"wires":[["755408d6.2374a8"]]},{"id":"bd7b0397.14b18","type":"api-call-service","z":"7329dbb4.98afe4","name":"","server":"456659de.370498","version":1,"debugenabled":false,"service_domain":"zwave","service":"set_config_parameter","entityId":"","data":"","dataType":"json","mergecontext":"","output_location":"","output_location_type":"none","mustacheAltTags":false,"x":590,"y":620,"wires":[[]]},{"id":"456659de.370498","type":"server","z":"","name":"Home Assistant","addon":true}]`

**Comment by pdong** [comment]
@nappyjim Sorry I missed this.  Your flow looks correct.  A couple things to check: are you using a dimmer or switch?  The config is set to use the switch so that might be the problem you're encountering.  I would attempt to trigger the zwave set_config manually to see if it's working (take NR out of the equation)

You can go to developer tools > services and do something like
![image](https://user-images.githubusercontent.com/5158502/101527227-937d0180-3942-11eb-8e45-11f8b2556d27.png)

and check if the color changes then.
